name: lyceumai
version: 1.0.0+1
publish_to: "none"
description: "An intelligent classroom app that transforms traditional learning into an interactive, AI-powered experience. Designed for both students and educators, it seamlessly integrates communication, collaboration, and automation to make learning more engaging and efficient."

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.20.2
  go_router: ^16.2.1
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  firebase_core: ^4.2.0
  flutter_sound: ^9.28.0
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.0.3
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  syncfusion_flutter_pdfviewer: ^31.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/banner_class.jpg
